spring:
  datasource:
    url: jdbc:sqlite:src/main/resources/db/maplewood_school.sqlite
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size=1
      minimum-idle=1
      connection-timeout=20000
  jackson:
    serialization:
      INDENT_OUTPUT: true
server:
  port: 8081